#!/usr/bin/env bash

# TPUT CONF :-:

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
MAGENTA=$(tput setaf 5)
WHITE=$(tput setaf 7)
BOLD=$(tput bold)
RESET=$(tput sgr0)

#######################

check_dependents() {
    if command -v figlet && command -v toilet && command -v lolcat; then
        menu
    else
        echo -e "${RED}Ferramentas necessárias não encontradas.${RESET}"
    fi
}

menu() {
    clear
    cat banner.txt | lolcat
    echo
    echo -ne "${WHITE}┏━━━━[DIGITE A URL]${RESET}\n${WHITE}┃\n┣▶${MAGENTA}[ Ex: www.google.com ]${RESET}\n┃\n${WHITE}┗━━➤ ${RESET}"
    read url
    link "$url"
}

link() {
    if [[ -n "$1" ]]; then
        curl -s "https://is.gd/create.php?format=simple&url=$1" > link.txt
        proto=$(tail -n1 link.txt | cut -d "/" -f1)
        domain=$(head -n1 link.txt | cut -d "/" -f4)
        opcao
    else
        clear
        echo -e "\n\n${RED}Verifique se a URL está correta...\n\n"
        exit 1
    fi
}

opcao() {
    echo
    read -ep "${RESET}${BOLD}Deseja Personalizar a URL [Y/N] " -n 1 -r ys
    if [[ "$ys" =~ ^[Yy]$ ]]; then
        echo -ne "\n\n${BOLD}Digite a Palavra Para a URL ${GREEN}[Ex: globo]${RESET} >> "
        read palavra
        clear
        echo -e "\n\n${BOLD}URL: ${GREEN}$proto//$palavra@is.gd/$domain\n\n"

    elif [[ "$ys" =~ ^[Nn]$ ]]; then
        link=$(cat link.txt | tr -d '%')
        clear
        echo -e "\n\n${BOLD}URL: ${GREEN}$link\n\n"
    fi
    [[ -e "link.txt" ]] && rm -rf link.txt
}

check_dependents